routes/web.php
<?php

use Illuminate\Support\Facades\Input;
/*******************************************************************************************
 *                                  AUTH
 *******************************************************************************************/

Auth::routes();

/*******************************************************************************************
 *                                  BACKEND
 *******************************************************************************************/

Route::group(['prefix' => 'backend', 'middleware' => 'backend', 'namespace' => 'Backend'], function () {
    Route::get('/', ['uses' => 'BackendsController@index', 'as' => 'backend.index']);

    Route::group(['prefix' => 'users'], function () {
        Route::get('/myaccount', ['uses' => 'UsersController@myaccount', 'as' => 'users.myaccount']);
        Route::post('/profile/update', ['uses' => 'ProfilesController@update', 'as' => 'profile.update']);
        Route::delete('/massdelete', ['uses' => 'UsersController@massdelete', 'as' => 'users.massdelete']);
    });
    Route::resource('users', 'UsersController');

    Route::group(['prefix' => 'roles'], function () {
        Route::delete('/massdelete', ['uses' => 'RolesController@massdelete', 'as' => 'roles.massdelete']);
    });
    Route::resource('roles', 'RolesController');
    Route::group(['prefix' => 'permissions'], function () {
        Route::delete('/massdelete', ['uses' => 'PermissionsController@massdelete', 'as' => 'permissions.massdelete']);
    });
    Route::resource('permissions', 'PermissionsController');

    Route::group(['prefix' => 'models'], function () {
        Route::delete('/massdelete', ['uses' => 'DatasetsController@massdelete', 'as' => 'models.massdelete']);
    });
    Route::resource('models', 'DatasetsController');

    // Menu Management Page
    Route::get('/menu', function () {
        $menu = DB::table('tbl_menus')->orderBy('order', 'ASC')->get();
        return view('backend.menus.menu', ['menus' => $menu]);
    });

// Menu Manager
    Route::get('/managemenu', function () {
        $menu = DB::table('tbl_menus')->orderBy('order', 'ASC')->get();
        return view('backend.menus.menuManage', ['menus' => $menu]);
    });
// Menu Sorter Function
    Route::get('/order-menu', function () {
        $menu = DB::table('tbl_menus')->orderBy('order', 'ASC')->get();
        $itemID = Input::get('itemID');
        $itemIndex = Input::get('itemIndex');

        foreach ($menu as $value) {
            return DB::table('tbl_menus')
                ->where('menu_id', '=', $itemID)
                ->update(array('order' => $itemIndex));
        }
        return redirect()->route('backend.index');
    });

});

app/Models/Backend/Dataset.php
<?php

namespace App\Models\Backend;

use App\Models\Permission;
use Illuminate\Database\Eloquent\Model;

class Dataset extends Model
{
    protected $guarded = [];

    public function permissions()
    {
        return $this->hasMany(Permission::class);
    }
}

app/Models/Permission.php
<?php

namespace App\Models;

use App\Models\Backend\Dataset;
use App\Models\Role;
use Illuminate\Database\Eloquent\Model;

class Permission extends Model
{
    protected $guarded = [];

    public function dataset()
    {
        return $this->belongsTo(Dataset::class);
    }

    public function roles()
    {
        return $this->belongsToMany(Role::class);
    }
}

app/Models/Profile.php
<?php

namespace App\Models;

use App\Models\User;
use Illuminate\Database\Eloquent\Model;

class Profile extends Model
{
    protected $guarded = [];
    
    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function getAvatar($avatar)
    {
        return asset($avatar);
    }
}

app/Models/Role.php
<?php

namespace App\Models;

use App\Models\User;
use App\Models\Permission;
use Illuminate\Database\Eloquent\Model;

class Role extends Model
{
    protected $guarded = [];

    public function users()
    {
        return $this->belongsToMany(User::class);
    }

    public function permissions(){
        return $this->belongsToMany(Permission::class);
    }

}

app/Models/User.php
<?php

namespace App\Models;
use App\Models\Role;
use App\Models\Profile;
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable; 

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'password_confirmation'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function roles(){
        return $this->belongsToMany(Role::class);
    }
    public function profile(){
        return $this->hasOne(Profile::class);
    }
    public function hasAnyRole($roles){
        return null != $this->roles()->whereIn('name', $roles)->first();
    }
    public function hasRole($role){
        return null != $this->roles()->where('name', $role)->first();
    }
}

app/Http/Controllers/Backend/BackendsController.php
<?php

namespace App\Http\Controllers\Backend;
use App\Http\Controllers\Controller;

use Illuminate\Http\Request;

class BackendsController extends Controller
{
    public function index(){
        return view('backend.dashboard');
    }
}

app/Http/Controllers/Backend/DatasetsController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Models\Backend\Dataset;
use App\Http\Controllers\Controller;
use App\Http\Requests\Backend\DatasetsRequest;
use Illuminate\Http\Request;
use Session;

class DatasetsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('backend.models.index')->with('datasets', Dataset::all());
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('backend.models.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(DatasetsRequest $request)
    {
        Dataset::create([
            'name' => $request->name,
            'key' => str_slug($request->name),
            'description' => $request->description,
        ]);
        Session::flash('success', 'The model has been created');
        return redirect()->route('models.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        return view('backend.models.edit')->with('dataset', Dataset::find($id));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(DatasetsRequest $request, $id)
    {
        Dataset::find($id)->update([
            'name' => $request->name,
            'key' => str_slug($request->name),
            'description' => $request->description,
        ]);
        Session::flash('success', 'The model has been updated');
        return redirect()->back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {

    }

    public function massdelete(Request $request)
    {
        $checked = $request->input('id', []);
        foreach ($checked as $id) {
            Dataset::find($id)->delete();
        }
        Session::flash('success', 'The dataset(s) was successfully deleted');
        return redirect()->route('models.index');
    }
}

app/Http/Controllers/Backend/PermissionsController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Models\Backend\Dataset;
use App\Http\Controllers\Controller;
use App\Http\Requests\Backend\PermissionsRequest;
use App\Models\Permission;
use Illuminate\Http\Request;
use Session;

class PermissionsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('backend.permissions.index')->with('permissions', Permission::all());
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('backend.permissions.create')->with('models', Dataset::all());
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(PermissionsRequest $request)
    {
        Permission::create([
            'name' => ucwords($request->name),
            'slug' => str_slug($request->name),
            'description' => $request->description,
            'dataset_id' => $request->dataset_id
        ]);
        Session::flash('success', 'The permission was created successfully');
        return redirect()->route('permissions.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        return view('backend.permissions.edit')
        ->with('permission', Permission::find($id))
        ->with('models', Dataset::all());
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(PermissionsRequest $request, $id)
    {
        Permission::find($id)->update([
            'name' => ucwords($request->name),
            'slug' => str_slug($request->name),
            'description' => $request->description,
            'dataset_id' => $request->dataset_id
        ]);
        Session::flash('success', 'The permission has been updated successfully');
        return redirect()->back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function massdelete(Request $request)
    {
        $checked = $request->input('id', []);
        foreach ($checked as $id) {
            Permission::find($id)->delete();
        }
        Session::flash('success', 'The permission(s) was successfully deleted');
        return redirect()->route('permissions.index');
    }
}

app/Http/Controllers/Backend/ProfilesController.php
<?php

namespace App\Http\Controllers\Backend;

use Auth;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Backend\Profile;
use Session;
use App\Models\User;

class ProfilesController extends Controller
{
    public function update(Request $request)
    {
        // Fetch current user object
        $user = Auth::user();

        // Validate name,email field - email for each user should be unique
        $this->validate($request, [
            'name' => 'required',
            'email' => 'required|email',
        ]);

        $user->name = $request->name;
        $user->email = $request->email;
        
        // If avatar fied is filled in
        if ($request->hasFile('avatar')) {
            $avatar = $request->avatar;
            $avatar_new_name = time() . $avatar->getClientOriginalName();
            $avatar->move('uploads/avatars', $avatar_new_name);
            $user->profile->avatar = 'uploads/avatars/' . $avatar_new_name;
            // attact to the current user and save
            $user->profile->save();
        }

        //if password field is not empty
        if (!empty($request->password)) {
            $this->validate($request, [
                'password' => 'required|alpha_num|min:8|confirmed',
            ]);
            $user->password = bcrypt($request->password);
            $user->save();
            $user->profile->save();
            Auth::logout();
            Session::flash('success', 'You have changed your password, please log in again with your newly created password');            
        }

        //Save for User Model and Profile Model. Check one-to-one relationship
        $user->save();
        $user->profile->save();
        
        Session::flash('success', 'Profile was updated successfully');
        return redirect()->back();

    }
}

app/Http/Controllers/Backend/RolesController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Models\Backend\Dataset;
use App\Http\Controllers\Controller;
use App\Http\Requests\Backend\RolesRequest;
use App\Models\Permission;
use App\Repositories\Backend\Roles;
use App\Models\Role;
use Auth;
use Illuminate\Http\Request;
use Session;

class RolesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Roles $roles)
    {
        return view('backend.roles.index')
            ->with('roles', $roles->all())
            ->with('user', Auth::user());
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {   
        $p_ids = [];
        $models = Dataset::with('permissions')->get();
        $permissions = Permission::orderBy('name', 'asc')->get();
        return view('backend.roles.create')
            ->with(compact('permissions', 'models', 'p_ids'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(RolesRequest $request)
    {
        Role::create([
            'name' => ucfirst($request->name),
            'key' => str_slug($request->name),
            'description' => $request->description,
        ]);
        Session::flash('success', 'The role was successfully created');
        return redirect()->route('roles.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $models = Dataset::with('permissions')->get();
        $permissions = Permission::orderBy('name', 'asc')->get();
        $p_ids = [];
        $role = Role::find($id);
        foreach ($role->permissions as $p) {
            $p_ids[] = $p->id;
        }
        return view('backend.roles.edit')
            ->with(compact('permissions', 'models', 'p_ids', 'role'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(RolesRequest $request, $id)
    {
        $role = Role::find($id);
        $role->name = ucfirst($request->name);
        $role->key = str_slug($request->name);
        $role->description = $request->description;
        $role->permissions()->sync($request->permission);
        $role->save();
        Session::flash('success', 'The role ' . $request->name . ' was sucessfully updated');
        return redirect()->back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Role::find($id)->delete();
        Session::flash('success', 'The role was successfully deleted');
        return redirect()->back();
    }

    public function massdelete(Request $request)
    {
        $checked = $request->input('id', []);
        foreach ($checked as $id) {
            Role::find($id)->delete();
        }
        Session::flash('success', 'The role was successfully deleted');
        return redirect()->route('roles.index');
    }
}

resources/views/backend/models/create.blade.php
@extends('backend.master') @section('content')
<div class="row">
  <div class="col-sm-12">
    <div class="element-wrapper">
      <h6 class="element-header">
        Add New Role
      </h6>
      <div class="element-box">
        <form action="{{route('models.store')}}" method="post" enctype="multipart/form-data">
          {{csrf_field()}} 
          @include('backend.models.form')
          <div class="form-group">
            <button class="btn btn-primary" type="submit">
              Save
            </button>
            <a href="{{route('models.index')}}" class="btn btn-info">Back</a>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
@stop

resources/views/backend/models/edit.blade.php
@extends('backend.master') @section('content')
<div class="row">
  <div class="col-sm-12">
    <div class="element-wrapper">
      <h6 class="element-header">
        Edit Model
      </h6>
      <div class="element-box">
        <form action="{{route('models.update', ['id'=> $dataset->id])}}" method="post" enctype="multipart/form-data">
          {{csrf_field()}} 
          {{method_field('PUT')}}
          @include('backend.models.form')
          <div class="form-group">
            <button class="btn btn-primary" type="submit">
              Save Changes
            </button>
            <a href="{{route('models.index')}}" class="btn btn-info">Back</a>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
@stop

resources/views/backend/models/form.blade.php
<div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
    <label for="name">
        Model Name
    </label>
    <input name="name" type="text" class="form-control" value="{{old('name',$dataset->name ?? null)}}">
    <span class="help-block text-danger">
        <strong>{{ $errors->first('name') }}</strong>
    </span>
</div>
<div class="form-group{{ $errors->has('description') ? ' has-error' : '' }}">
    <label for="description">
        Model Description
    </label>
    <input name="description" type="text" class="form-control" value="{{old('description',$dataset->description ?? null)}}">
    <span class="help-block text-danger">
        <strong>{{ $errors->first('description') }}</strong>
    </span>
</div>

resources/views/backend/models/index.blade.php
@extends('backend.master') 
@section('content')
<div class="row">
	<div class="col-sm-12">
		<div class="element-wrapper">
			<h6 class="element-header">
				Models
			</h6>
			<form class="form" action="{{route('models.massdelete')}}" method="post">
			{{csrf_field()}}
			{{method_field('DELETE')}}
			<div class="element-box">
			<div class="element-box-content">
			<div class="btn-group">
				<a href="{{route('models.create')}}" class="btn btn-primary">Add New Model</a>
			</div>
			<div class="btn-group">
				<button  class="btn btn-danger" id="bulk-delete" type="submit" name="bulkdelete" value="bulkdelete"  onclick="return confirm('Are you sure you want to delete the selected record(s)?')"><i class="os-icon os-icon-ui-15"></i> Delete</button>
			</div>
			</div>
			</div>
			<div class="element-box">
				<div class="table-responsive">
					<table id="datatable" class="table table-striped">
						<thead>
							<tr>
								<th><input type="checkbox" id="selectall" class="checked" {{$datasets->count() > 0 ? '':'disabled'}} /></th>
								<th> # </th>								
								<th>Name</th>
								<th>Key</th>
								<th>Description</th>                               
								<th>Actions</th>
							</tr>
						</thead>
						<tbody>
							@foreach($datasets as $key=>$dataset)
							<tr>
								<td><input type="checkbox" name="id[]" value="{{$dataset->id}}" class="check-all"></td>
								<td>{{++$key}}</td>								
								<td>{{$dataset->name}}</td>
								<td>{{$dataset->key}}</td>
								<td>{{$dataset->description}}</td>                               
								<td class="row-actions">
									<a href="{{route('models.edit',['id'=>$dataset->id])}}">
										<i class="os-icon os-icon-pencil-2"></i>
									</a>									
								</td>
							</tr>
							@endforeach
						</tbody>
					</table>
				</div>
			</div>
			</form>
		</div>
	</div>
</div>
@endsection
@include('backend.asset-partials.datatables')
@include('backend.asset-partials.form-function')